/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cppImp_highlightIDE */

#ifndef _Included_cppImp_highlightIDE
#define _Included_cppImp_highlightIDE
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cppImp_highlightIDE
 * Method:    highlightCPP
 * Signature: (Ljava/lang/String;Z)[LcppImp/ColorJNI;
 */
JNIEXPORT jobjectArray JNICALL Java_cppImp_highlightIDE_highlightCPP
  (JNIEnv *, jclass, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
